language: java
jdk:
- oraclejdk8
sudo: required
addons:
  sonarqube:
    token: SONAR_TOKEN
script: mvn clean package
after_success:
- mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache