language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: E90zz++xuqT1uU7LDD+J+bFzcBTxEQje9InERnfwc3obgo3RH82P/wIyEfQI5K3aquSW9QZNvWaXbRhU+7IT5kITDwyjg1BcFqOvJ2n0BkKFVIIYsB0/QoQrZzoxfH6C6MMzW8WMEH+iLS2yi7mMCd/MWlcZKRFzzF1ej8nmslt0zwWRCOuqKdKPV8qRQW1/SP+4unU0j45nI4N9bxgNsYZ0IKNvHW3eY02Bg9MGzevyF6a1DaWLJU4kNAxjfU/OfKf3cu1MDiNvSj3JqC2tixjdY0BTR8SGBnmmp/GC+pmIB1Nm2YaEKbD7NS8xyEPMJuIGuHnLeiLYxCrEdNBG7+5u3bcD+1auBLATEZA8JnTN8mwlxvfB3aZP4bq2rs6LVkfmtKzAKy6Pbztxbu0hckqA7nA9FHimQm9vK7iIWtPRCAu/bEFkgBYG87y1kRr8/FZ8OyDH0r0KMMOBqxCFudbR4NKRHNZTTroE7z4Ox7Uq+OdoUFOMQFIbAdv8sRue61DcCd4JZY9M0FfmV+AJ6jtKCNwM7KGc1AgCdf68GHZvOxnaJzCcw6vCL5SVXveEyAJ/OxKLipkRprDk8OkJ5rhU0VIaKu+yuusNAeu1P/vMOiLD9LE8Qwr0vzJ1vSv/wLn+KvhMQavEJx3oPy3e3n83RCzCWnqnrxAL4kthtV8=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
#cache:
#  directories:
#  - $HOME/.m2/repository
#  - $HOME/.sonar/cache
notifications:
  email: false
#env:
#  global:
#    secure: E90zz++xuqT1uU7LDD+J+bFzcBTxEQje9InERnfwc3obgo3RH82P/wIyEfQI5K3aquSW9QZNvWaXbRhU+7IT5kITDwyjg1BcFqOvJ2n0BkKFVIIYsB0/QoQrZzoxfH6C6MMzW8WMEH+iLS2yi7mMCd/MWlcZKRFzzF1ej8nmslt0zwWRCOuqKdKPV8qRQW1/SP+4unU0j45nI4N9bxgNsYZ0IKNvHW3eY02Bg9MGzevyF6a1DaWLJU4kNAxjfU/OfKf3cu1MDiNvSj3JqC2tixjdY0BTR8SGBnmmp/GC+pmIB1Nm2YaEKbD7NS8xyEPMJuIGuHnLeiLYxCrEdNBG7+5u3bcD+1auBLATEZA8JnTN8mwlxvfB3aZP4bq2rs6LVkfmtKzAKy6Pbztxbu0hckqA7nA9FHimQm9vK7iIWtPRCAu/bEFkgBYG87y1kRr8/FZ8OyDH0r0KMMOBqxCFudbR4NKRHNZTTroE7z4Ox7Uq+OdoUFOMQFIbAdv8sRue61DcCd4JZY9M0FfmV+AJ6jtKCNwM7KGc1AgCdf68GHZvOxnaJzCcw6vCL5SVXveEyAJ/OxKLipkRprDk8OkJ5rhU0VIaKu+yuusNAeu1P/vMOiLD9LE8Qwr0vzJ1vSv/wLn+KvhMQavEJx3oPy3e3n83RCzCWnqnrxAL4kthtV8=
